import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { store } from "@/lib/store";
import { essayStore } from "@/lib/essay-store";
import { inventoryStore } from "@/lib/inventory-store";
import { musicStore } from "@/lib/music-store";
import { letterStore } from "@/lib/letter-store";
import { userStore } from "@/lib/user-store";
import { sourceStore } from "@/lib/source-store";
import { PageShell } from "@/app/_components/page-shell";
import { HomeEntryBlock } from "@/app/_components/site/home-entry";
import { buildHomeTimeline, yearMarks } from "@/lib/home-timeline";
import { ProfileMark } from "@/app/_components/site/profile-mark";
import { isHostEmail, getSession } from "@/lib/auth";
import { checkTenantVisibility } from "@/lib/tenant-visibility";
import { tenantBase, tenantAbsoluteBase, normalizeUrl } from "@/lib/tenant-domains";

export const dynamic = "force-dynamic";

// Soft-privacy default for tenant pages: keep them out of search indexes and
// out of crawlers' link graphs. The URL is still reachable to anyone who has
// it — this just stops "search myself, find my stream" surprises. Real
// per-post privacy (public / friends / private) is a future slice.
//
// OpenGraph fields are populated for friends-sharing-on-WhatsApp: the share
// sheet message includes the home URL; the receiving app fetches the URL,
// reads these `og:*` tags, and renders the preview card. The image itself
// is generated by `opengraph-image.tsx` in this directory (Next auto-wires
// it into the metadata).
export async function generateMetadata({
  params,
}: {
  params: Promise<{ handle: string }>;
}) {
  const { handle } = await params;
  const user = await userStore.getByHandle(handle);
  const displayName = user?.displayName || handle;
  const title = user ? `${displayName} · Nearstream` : "Nearstream";
  const description = user
    ? `${displayName} on Nearstream — a quieter way to share with people you actually know.`
    : "Nearstream — a quieter way to share with people you actually know.";
  return {
    title,
    description,
    robots: { index: false, follow: false },
    openGraph: {
      title,
      description,
      type: "profile",
      siteName: "Nearstream",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}


function formatShort(iso: string): string {
  const d = new Date(iso);
  const month = d.toLocaleString("en", { month: "short" });
  return `${month} ${d.getDate()}`;
}

function formatLetterDate(iso: string): string {
  const d = new Date(iso);
  const month = d.toLocaleString("en", { month: "long" });
  return `${month} ${d.getDate()}`;
}

type Props = {
  params: Promise<{ handle: string }>;
  searchParams: Promise<{ friend?: string; "friend-error"?: string }>;
};

export default async function TenantHome({ params, searchParams }: Props) {
  const { handle } = await params;
  const { friend, "friend-error": friendError } = await searchParams;
  const user = await userStore.getByHandle(handle);
  if (!user) notFound();

  const isHost = isHostEmail(user.email);

  const [letter, allEntries, allEssays, allInventory, allTracks, session] =
    await Promise.all([
      letterStore.get(user.id),
      store.list(user.id),
      essayStore.list(user.id),
      inventoryStore.list(user.id),
      musicStore.list(user.id),
      getSession(),
    ]);

  // Slice 36 — site privacy. Owner always sees their own tenant. Everyone
  // else obeys the tenant's `sitePrivacy` preference (friends default for
  // new users; host defaults to public). Sign-in-needed sends visitors to
  // /login so they can auth as themselves; not-for-you 404s so we don't
  // leak that a private tenant exists.
  const gate = checkTenantVisibility(user, session);
  if (!gate.allowed) {
    if (gate.reason === "sign-in") {
      redirect(`/login?next=${encodeURIComponent(`/${handle}`)}&reason=private-tenant`);
    }
    notFound();
  }

  // Owner sees everything (including their own private entries); anyone else
  // only sees public ones. Letter has no per-entry visibility yet — it's the
  // host's broadcast slot.
  const isOwner = session?.userId === user.id;

  // "Add as friend" CTA — only shown to signed-in visitors who aren't the
  // owner. We probe their reader for an existing source pointing at this
  // tenant so we can render the already-following confirmation instead.
  let friendState: "none" | "self" | "signed-out" | "following" | "not-following" =
    "signed-out";
  if (session) {
    if (isOwner) {
      friendState = "self";
    } else {
      const sources = await sourceStore.list(session.userId);
      const targetSite = tenantAbsoluteBase(
        user.handle,
        process.env.NEARSTREAM_SITE_URL ?? "",
      );
      const targetFeed = `${targetSite}/rss.xml`;
      // Normalized so a stale row stored as `nearstream.app` (no www) or
      // under a superseded NEARSTREAM_SITE_URL still matches today's
      // canonical form and we don't offer to re-add someone we already
      // follow.
      const normFeed = normalizeUrl(targetFeed);
      const normSite = normalizeUrl(targetSite);
      const alreadyFollowing = sources.some(
        (s) =>
          normalizeUrl(s.feedUrl) === normFeed ||
          normalizeUrl(s.siteUrl ?? "") === normSite ||
          // Also match instance-relative paths, in case a source was added
          // before tenantAbsoluteBase was wired in.
          s.siteUrl === `/${user.handle}`,
      );
      friendState = alreadyFollowing ? "following" : "not-following";
    }
  }
  const base = tenantBase(handle);

  // One document, not five sections. Everything the viewer may see, newest
  // first, each entry carrying its own age treatment.
  const timeline = buildHomeTimeline({
    entries: allEntries,
    essays: allEssays,
    inventory: allInventory,
    tracks: allTracks,
    base,
    isOwner,
  });
  const marks = yearMarks(timeline);

  const navLinkClasses =
    "font-mono text-[11px] uppercase tracking-[0.2em] text-muted transition-colors hover:text-foreground";
  const sectionLabelClasses =
    "block font-mono text-[10px] uppercase tracking-[0.25em] text-muted-soft transition-colors hover:text-foreground";

  return (
    <PageShell
      rightNav={
        <>
          <Link href={`${base}/library`} className={navLinkClasses}>
            Library
          </Link>
          <Link href="/studio" className={navLinkClasses}>
            Studio →
          </Link>
        </>
      }
    >
      <section className="flex flex-1 justify-center px-6">
        {/* Paper is never perfectly flat. Fixed, pointer-transparent,
            almost subliminal — see globals.css. */}
        <div className="tooth" aria-hidden />
        <div className="relative w-full max-w-[34rem] pt-12 pb-32">
          {/* Hero — everyone renders the profile mark they picked in
              onboarding (variant 0 = original signature parameters, so the
              default still looks like the piece). */}
          <div className="flex flex-col items-center">
            <ProfileMark
              variantIndex={user.profileMark}
              size={280}
              className="block"
              ariaLabel={`${user.displayName || handle} — profile mark`}
            />
            <h1 className="mt-6 text-[17px] font-normal text-foreground">
              {user.displayName || handle}
            </h1>
            <FriendAffordance
              state={friendState}
              handle={user.handle}
              displayName={user.displayName || user.handle}
              flash={friend === "added" ? "added" : friendError ? "error" : null}
              flashMessage={friendError}
            />
          </div>

          {letter ? (
            <div className="mt-10">
              <div className="mb-6 font-mono text-[10px] uppercase tracking-[0.3em] text-muted-soft">
                {formatLetterDate(letter.updatedAt)} ─
              </div>
              <p className="whitespace-pre-wrap text-base leading-relaxed text-foreground">
                {letter.body}
              </p>
              <div className="mt-6 text-right font-mono text-[10px] uppercase tracking-[0.3em] text-muted-soft">
                — {(user.displayName || handle).split(" ")[0][0] ?? "A"}.
              </div>
            </div>
          ) : null}

          {timeline.length === 0 ? (
            <p className="mt-16 text-sm leading-relaxed text-muted">
              Nothing here yet.
            </p>
          ) : (
            <div className="mt-14">
              {timeline.map((entry) => (
                <HomeEntryBlock
                  key={`${entry.kind}-${entry.id}`}
                  entry={entry}
                  date={formatShort(entry.publishedAt)}
                />
              ))}
            </div>
          )}

          {/* The year — one mark per entry, tallest for the things that took
              the most out of you. The rhythm of a year rather than a wall of
              thumbnails, and the only "how much is here" signal on a page
              that never paginates. */}
          {marks.length > 1 && (
            <div style={{ marginTop: "4rem" }} className="border-t border-border pt-5">
              <div className="mb-3 flex items-baseline justify-between">
                <span className={sectionLabelClasses}>This year</span>
                <span className="font-mono text-[9.5px] uppercase tracking-[0.22em] text-muted-soft tabular-nums">
                  {timeline.length} {timeline.length === 1 ? "entry" : "entries"}
                </span>
              </div>
              <div className="flex h-8 items-end gap-[2px]" aria-hidden>
                {marks.map((m, i) => (
                  <span
                    key={i}
                    className="w-[2px] flex-none rounded-[1px] bg-foreground/35"
                    style={{ height: `${m.height}%`, opacity: m.opacity }}
                  />
                ))}
              </div>
            </div>
          )}


          {/* Elsewhere — host-only for now; tenant elsewhere links are a
              future primitive. */}
          {isHost && (
            <section style={{ marginTop: "4.5rem" }}>
              <div className={sectionLabelClasses + " mb-8"}>Elsewhere</div>
              <ul className="mt-8 flex flex-col gap-3">
                <li>
                  <a
                    href="https://www.instagram.com/moving.points/"
                    className="text-[14px] text-muted transition-colors hover:text-foreground"
                  >
                    moving.points
                  </a>
                </li>
                <li>
                  <a
                    href={`${base}/rss.xml`}
                    className="text-[14px] text-muted transition-colors hover:text-foreground"
                  >
                    rss
                  </a>
                </li>
                <li>
                  <a
                    href="mailto:alessandroxborelli@gmail.com"
                    className="text-[14px] text-muted transition-colors hover:text-foreground"
                  >
                    say hi
                  </a>
                </li>
              </ul>
            </section>
          )}

          {!isHost && (
            <section style={{ marginTop: "4.5rem" }}>
              <div className={sectionLabelClasses + " mb-8"}>Elsewhere</div>
              <ul className="mt-8 flex flex-col gap-3">
                <li>
                  <a
                    href={`${base}/rss.xml`}
                    className="text-[14px] text-muted transition-colors hover:text-foreground"
                  >
                    rss
                  </a>
                </li>
              </ul>
            </section>
          )}
        </div>
      </section>
    </PageShell>
  );
}

type FriendAffordanceProps = {
  state: "none" | "self" | "signed-out" | "following" | "not-following";
  handle: string;
  displayName: string;
  flash: "added" | "error" | null;
  flashMessage?: string;
};

// Tiny CTA strip under the hero. Signed-out visitors see nothing — Nearstream
// is opt-in, not a discovery surface. The owner sees nothing either; this is
// their own page. Everyone else gets one of two states:
//   - not following → "Add as friend" form (POSTs to /api/friends/follow)
//   - already following → "Following · Open reader" link
// The `flash` slot reuses the same chrome to confirm "added" or surface an
// error after the POST redirect.
function FriendAffordance({
  state,
  handle,
  displayName,
  flash,
  flashMessage,
}: FriendAffordanceProps) {
  if (state === "self" || state === "signed-out" || state === "none") {
    return null;
  }
  if (flash === "added" || state === "following") {
    return (
      <div className="mt-6 flex flex-col items-center gap-2">
        <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-soft">
          ✓ {flash === "added" ? "Added" : "Following"}
          <span className="text-border"> · </span>
          <Link
            href="/reader"
            className="text-muted transition-colors hover:text-foreground"
          >
            Open reader →
          </Link>
        </span>
      </div>
    );
  }
  return (
    <div className="mt-6 flex flex-col items-center gap-2">
      <form action="/api/friends/follow" method="POST">
        <input type="hidden" name="handle" value={handle} />
        <button
          type="submit"
          className="border border-border px-4 py-2 font-mono text-[10px] uppercase tracking-[0.22em] text-foreground transition-colors hover:border-foreground hover:bg-foreground hover:text-background"
        >
          Add {displayName.split(" ")[0]} as friend
        </button>
      </form>
      {flash === "error" && flashMessage ? (
        <p
          role="alert"
          className="font-mono text-[10px] uppercase tracking-[0.18em] text-foreground/80"
        >
          {flashMessage}
        </p>
      ) : null}
    </div>
  );
}
